### ISSUE TITLE
TypeError: Cannot read property 'N' of undefined

### ISSUE THREAD

**Issue by DylanCa** [awslabs/aws-lambda-redshift-loader#128]
Hi,

I have an issue I can't deal with. When I test the Lambda, the .csv is recognized and "batched" and the Redshift configuration is properly loaded, but after that, I have an error and the data is not put into Redshift.

Here's the error : http://puu.sh/wxhqv/72435c8469.png

```
TypeError: Cannot read property 'N' of undefined
at Response.<anonymous> (/var/task/index.js:614:112)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:360:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)
```

Can anyone help me out here ? Thank you !

**Comment by DylanCa** [comment]
Managed to get rid of this error by deleting `+ config.batchSizeBytes.N` of the line 614, I don't know if that can help.

**Comment by DylanCa** [comment]
Yep, now I have another issue 

```
2017-06-29T14:57:02.156Z	35252753-5cdb-11e7-8863-fb52b8046f46	Batch count 1 reached
2017-06-29T14:57:02.156Z	35252753-5cdb-11e7-8863-fb52b8046f46	Current batch age of 0.15599989891052246 seconds below batch timeout: 1
2017-06-29T14:57:02.156Z	35252753-5cdb-11e7-8863-fb52b8046f46	Batch size 0 bytes reached
2017-06-29T14:57:02.227Z	35252753-5cdb-11e7-8863-fb52b8046f46	TypeError: Cannot read property 'Attributes' of undefined
    at /var/task/index.js:681:17
    at /var/task/common.js:200:2
    at /var/task/node_modules/async/dist/async.js:906:16
    at next (/var/task/node_modules/async/dist/async.js:5175:18)
    at Response.<anonymous> (/var/task/common.js:191:7)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
```
