### ISSUE TITLE
TypeError: Cannot read property 'Attributes' of undefined

### ISSUE THREAD

**Issue by exolab** [awslabs/aws-lambda-redshift-loader#129]
Still trying to get this to work. Now encountering a different error.

2017-06-30T12:23:27.574Z	ea5111f1-5d8e-11e7-9c43-95f5ad025e3f	TypeError: Cannot read property 'Attributes' of undefined
at /var/task/index.js:681:17
at /var/task/common.js:200:2
at /var/task/node_modules/async/dist/async.js:906:16
at next (/var/task/node_modules/async/dist/async.js:5175:18)
at Response.<anonymous> (/var/task/common.js:191:7)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:360:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)

**Comment by alexsambacanada** [comment]
I am running into this as well.  Any thoughts? @IanMeyers

**Comment by njsaunders** [comment]
+1 - Any ideas?

**Comment by ixalon** [comment]
Fixed by #130

**Comment by alexsambacanada** [comment]
Did the trick thanks!!

**Comment by axiomoixa** [comment]
I have the same issue on version 2.5.0
`2018-08-24T09:26:00.959Z	b5c917a4-a77f-11e8-a82a-9168a3a7011c	TypeError: Cannot read property 'Attributes' of undefined
at /var/task/index.js:681:17
at /var/task/common.js:200:2
at /var/task/node_modules/async/dist/async.js:906:16
at next (/var/task/node_modules/async/dist/async.js:5175:18)
at Response.<anonymous> (/var/task/common.js:191:7)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)`
