### ISSUE TITLE
Is bad many "ConditionalCheckFailedException" in log?

### ISSUE THREAD

**Issue by carlosrmendes** [awslabs/aws-lambda-redshift-loader#155]
In the logs of the function I have multiple (too many) message likes this:
```
{ ConditionalCheckFailedException: The conditional request failed
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'The conditional request failed',
code: 'ConditionalCheckFailedException',
time: 2018-05-14T18:43:53.181Z,
requestId: '2IVIAA06LEFJ2OEVCS23PJBJ3RVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 9.420444526163118 }
```

I check in the DynamoDB Error Handling docs that _**_ConditionalCheckFailedException_**_  occurs when _"You specified a condition that evaluated to false. For example, you might have tried to perform a conditional update on an item, but the actual value of the attribute did not match the expected value in the condition."_

My doubt is if that error in DynamoDB can prevent a file in S3 to be copied to Redshift, since in the log message that error appears as non retryable.

**Comment by IanMeyers** [comment]
Hello - the loader uses conditional updates to ensure load process allocation is singular to threads, and so this is not something you should worry about. That said, you shouldn't see these logs normally. Also having a large number of these is typically a sign that your batch size is too small.

**Comment by carlosrmendes** [comment]
I have a batch size of 100 files with a timeout of 120secs and yesterday with an average of 2 files uploaded to S3 per minute.
I'm using the latest version: _AWSLambdaRedshiftLoader-2.6.1_

**Comment by IanMeyers** [comment]
That's fine then.
