### ISSUE TITLE
TypeError: Cannot read property 'Key' of undefined

### ISSUE THREAD

**Issue by alexsp1999** [awslabs/aws-lambda-redshift-loader#160]
I am trying to implement aws-lambda-redshift-loader using an ec2 instance and I am not sure what is going wrong with my configuration.

Any tips would be greatly appreciated

This is the full error message from my ec2 instance terminal:

`
`TypeError: Cannot read property 'Key' of undefined`

    at /home/ec2-user/aws-lambda-redshift-loader/common.js:392:36
    at Array.map (native)
    at Response.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/common.js:391:51)
    at Request.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:26:10
`

**Comment by IanMeyers** [comment]
This is (probably) fixed in dec2f81.
