### ISSUE TITLE
Better retry strategy for failed loads.

### ISSUE THREAD

**Issue by davinchia** [awslabs/aws-lambda-redshift-loader#161]
Hi Ian,

We are running into the situation where loads timeout at certain times of the day because the cluster is under heavy utilisation. Looking at #68 as reference, we’ve already tried to tune this as much as possible. Our lambda timeout is set to the max (5 minutes). Our BatchSize and BatchSizeBytes are set to arbitrarily high numbers (128, 128GB) such that our BatchTimeoutSecs (600) is what is triggering the loads.

Error logs show this is due to redshift timing out:
`Cluster Load Failure error: abort query on Cluster OurCluster.redshift.amazonaws.com`

We have tried to remedy this by manually running the copy queries and the reprocess batch script. This is time intensive and we are hoping for a way to automate this. 

One suggestion we have is adding configuration options to the loader to automatically return failed files from a 'processed' state to a 'pending' state (not sure I'm using the right terminology), ready to be pick up again by the original loader. Some form of an automatic retry strategy. Something else good to have in this scenario is a configurable retry wait time, static or dynamic, to prevent loading into a maybe already overloaded cluster. 

One other idea we had was to play around with the lambda's retry settings. Any thoughts on that?

Otherwise, do you have any other suggestion/ideas which might help?

Thanks!

**Comment by IanMeyers** [comment]
Sure - you can use the reprocessBatch script to process these failed batches, and there is now https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/failedBatchReprocessingLambda.js which you can plugin to the failed batch SNS pipeline with your own logic to try and automate this. I would also suggest that monitoring the overall runtime of the function and lowering the batchSize during busy times might be an option.

**Comment by chrisjameswilliams** [comment]
I have the same use case as davinchia.

The failedBatchReprocessingLambda does not delete the entry from the processed files table so if you attempt to use this, you'll receive the File xxx Already Processed.

Would it be possible to include this? I'd like to reprocess a batch on error without needing to be aware of or tied to the implementation specifics.

**Comment by IanMeyers** [comment]
It looks like we had a workaround in the core module that was changed and rendered this broken. Apologies all. Am fixing now...

**Comment by IanMeyers** [comment]
Can you please retest with 060023c? This moves the current batch designation, if there is one, onto a list value that tracks previous batches, which is enough for the primary handler to know that it needs to reprocess the file without requiring deletion of the LambdaProcessedFiles entry. Hopefully this will work for you.

**Comment by chrisjameswilliams** [comment]
Thanks for the quick response @IanMeyers .

I think there are still 3 problems:-

failedBatchReprocessingLambda line 94:-
I think this should be event.Records[0].Sns.Message (not event.Records[0].Sns.MessageAttributes;) ?
looking at the example failure notifications I've seen.

when the batch is set to error state:-
TypeError: omitFiles.indexOf is not a function
    at /var/task/batchOperations.js:303:51
    at Array.map (native)
    at /var/task/batchOperations.js:302:49
    at Response.<anonymous> (/var/task/batchOperations.js:394:13)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)

when batch is set to reprocessing state:-
TypeError: callback is not a function
    at /var/task/batchOperations.js:294:33
    at Response.<anonymous> (/var/task/batchOperations.js:392:13)

**Comment by IanMeyers** [comment]
Sorry about these. The first in your list is addressed in 2.6.4 b7d4170, which now passes both the message and the attributes to the processing function.

For the second, b7d4170 should address this issue.

I believe that the third issue you cite is related to the second bug that's now fixed.

**Comment by chrisjameswilliams** [comment]
@IanMeyers 

Identified 2 problem:=

failedBatchReprocessingLambda.js

I think the message needs to be parsed
var message = JSON.parse(event.Records[0].Sns.Message);

batchOperation.js
The following block is hit but the reprocessFile funtion is not invoked.
 async.map(processFiles, function (item) {
                                console.log("item: " + JSON.stringify(item));
                                common.reprocessFile.bind(undefined, dynamoDB, s3, region, item, function(err) {callback(err);});
                            },

Sorry I would create a PR but my javascript knowledge is very limited.

Changing it to common.reprocessFile(dynamoDB, s3, region, item, undefined); fixes the problem.
