### ISSUE TITLE
TypeError: Cannot read property 'Key' of undefined

### ISSUE THREAD

**Issue by ericeche** [awslabs/aws-lambda-redshift-loader#173]
Running the latest zip file from https://aws.amazon.com/blogs/big-data/a-zero-administration-amazon-redshift-database-loader/

I am getting the following error, any help will be appreciated:

Additional Copy Options to be added > 
If Encrypted Files are used, Enter the Symmetric Master Key Value > 
Creating Tables in Dynamo DB if Required
Table LambdaRedshiftProcessedFiles already exists
Table LambdaRedshiftBatches already exists
Table LambdaRedshiftBatchLoadConfig already exists
Creating S3 Event Source for s3://redshiftapcd/
/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'Key' of undefined
    at /Users/eecheverri/aws-lambda-redshift-loader/common.js:392:37
    at Array.map (<anonymous>)
    at Response.<anonymous> (/Users/eecheverri/aws-lambda-redshift-loader/common.js:391:51)
    at Request.<anonymous> (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/eecheverri/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:26:10

**Comment by ericeche** [comment]
sziebold-1416:aws-lambda-redshift-loader eecheverri$ node --version
v10.10.0

**Comment by IanMeyers** [comment]
Can you please retest against 2.6.5: a959f5f?
