### ISSUE TITLE
No configuration found for <bucket-name>/prefix

### ISSUE THREAD

**Issue by kafkaguru** [awslabs/aws-lambda-redshift-loader#174]
Hello, I have the same issue as #24 as well. I am on the latest version (`v2.6.5`)
Running `node setup.js` proceeded without any issues
The logs are as follows:
```
2018-09-28T19:15:51.628Z	7ba537f3-c352-11e8-af1f-257dfc5e15e6	No Configuration Found for kpi-automation-lambda-spike/kafka/sink/dat.kpi.crmidentity.v1.incoming.avro
2018-09-28T19:15:51.628Z	7ba537f3-c352-11e8-af1f-257dfc5e15e6	{ ResourceNotFoundException: Requested resource not found
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Requested resource not found',
code: 'ResourceNotFoundException',
time: 2018-09-28T19:15:51.628Z,
requestId: 'USJ8F6I678A35OQK9VHAGFA887VV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 11.904977472482148 }
```
The user used to run `setup.js` as well as the role the lambda uses have all the appropriate permissions:
```
{
  "Effect": "Allow",
  "Action": [
    "s3:*",
    "kms:*",
    "dynamodb:*",
    "sns:*"
    ],
  "Resource": [
       "*"
   ]
}
```

The batch load config is as follows:

<img width="582" alt="screen shot 2018-09-28 at 1 57 04 pm" src="https://user-images.githubusercontent.com/9084149/46233142-78f07c00-c326-11e8-8236-fa0f4f024748.png">

```
{
  "accessKeyForS3": "****",
  "batchSize": 3,
  "batchTimeoutSecs": 120,
  "currentBatch": "ff775d89-f1c4-47a2-9ae4-a913f48d05d1",
  "dataFormat": "JSON",
  "failedManifestKey": "redshift-lambda/manifests/error",
  "failureTopicARN": "arn:aws:sns:us-east-1:kpi-automation-lambda-s3-to-redshift-error",
  "filenameFilterRegex": "*.json",
  "ignoreCsvHeader": true,
  "loadClusters": [
    {
      "clusterDB": "dev",
      "clusterEndpoint": "kpi-automation-lambda-spike-2.****.us-east-1.redshift.amazonaws.com",
      "clusterPort": 5439,
      "connectPassword": "****",
      "connectUser": "awsuser",
      "targetTable": "crm_identity",
      "truncateTarget": false,
      "useSSL": false
    }
  ],
  "manifestBucket": "kpi-automation-lambda-spike",
  "manifestKey": "redshift-lambda/manifests/success",
  "s3Prefix": "kpi-automation-lambda-spike/kafka/sink/dat.kpi.crmidentity.v1.incoming.avro",
  "secretKeyForS3": "****",
  "successTopicARN": "arn:aws:sns:us-east-1:kpi-automation-lambda-s3-to-redshift-success",
  "version": "2.6.5"
}
```

I changed the constants for the dynamo table names and KMS alias to match what we are allowed to create in our environment. 

Any glaring issues I'm missing?

**Comment by kafkaguru** [comment]
So I figured out the issue. I had change the constants on my local machine but the zip file I uploaded to the lambda still had the old unchanged constants. 

Thanks :)
