### ISSUE TITLE
Issue running setup.js

### ISSUE THREAD

**Issue by andrewrguy** [awslabs/aws-lambda-redshift-loader#18]
I just ran node setup.js for the first time and I got this output. I did run export AWS_REGION=us-east-1 before this

```
andrews-mbp:aws-lambda-redshift-loader andrewguy$ node setup.js
Enter the Region for the Redshift Load Configuration > us-east-1
Enter the S3 Bucket & Prefix to watch for files > ttgredshift/logload
Enter a Filename Filter Regex > error-csv.*
Enter the Cluster Endpoint > ttg-reporting.blahbalh..
Enter the Cluster Port > 5439
Enter the Database Name > reporting
Enter the Table to be Loaded > tablename
Should the Table be Truncated before Load? (Y/N) > n
Enter the Database Username > reporting
Enter the Database Password > MyPassword
Unknown Error during Customer Master Key describe
Error during resolution of Customer Master Key
/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
TypeError: Cannot read property '1' of null
    at Object.toLambdaStringFormat (/Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:236:32)
    at /Users/andrewguy/src/aws-lambda-redshift-loader/setup.js:139:19
    at /Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:124:11
    at Response.<anonymous> (/Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:102:16)
    at Request.<anonymous> (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

**Comment by IanMeyers** [comment]
Hello,

Sorry to hear you have an issue with this. Can you please confirm that the user credentials applied to your session where you are running the setup.js has rights to the AWS Key Management Service, specifically kms:DescribeKey, kms:GetKeyPolicy and kms:Encrypt?

Thx,

Ian

**Comment by IanMeyers** [comment]
I've also just pushed a small update to kmsCrypto.js that should result in a better error message than what you are getting now.

**Comment by andrewrguy** [comment]
Ian, thanks for the quick response. I did a pull and re ran the setup. The new error message is below:

```
Unknown Error during Customer Master Key describe
Error during resolution of Customer Master Key
/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
TypeError: Cannot read property 'length' of null
    at Object.toLambdaStringFormat (/Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:222:14)
    at /Users/andrewguy/src/aws-lambda-redshift-loader/setup.js:139:19
    at /Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:105:11
    at Response.<anonymous> (/Users/andrewguy/src/aws-lambda-redshift-loader/kmsCrypto.js:83:12)
    at Request.<anonymous> (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/andrewguy/src/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

I'm running with credentials in .aws/credentials that have this policy:
{
  "Statement": [
    {
      "Effect": "Allow",
      "NotAction": "iam:_",
      "Resource": "_"
    }
  ]
}

That should work, or no? Is KMS categorized under IAM?

Thanks,
Andy

**Comment by IanMeyers** [comment]
So not much better of an error message then. You will need kms :\* grants to use so, a well as dynamo db write privileges.

**Comment by andrewrguy** [comment]
Once I ran export AWS_.... instead of relying on the credentials file, the script completed. Why would it not read my credential file? the permissions seem fine on it.

**Comment by IanMeyers** [comment]
For the javascript SDK, it has to be in your home folder/.aws/credentials. Was that the path for the file?

**Comment by andrewrguy** [comment]
Yes, it is definitely in there:
/Users/andrewguy/.aws/credentials
I believe this happened with another AWS service before on my system..hmmm. Anyway, I believe this issue can be closed, since the original problem has been solved.
