### ISSUE TITLE
TypeError: Cannot read property 'L' of undefined

### ISSUE THREAD

**Issue by singhrcode** [awslabs/aws-lambda-redshift-loader#187]
When i try load sample data provided then in cloudwatch logs i get this error

```

> 2019-02-26T04:39:34.746Z b57cd446-e3d7-47e9-95c7-3c2ff6bbbf16 Found Redshift Load Configuration for randy-lambda-loader/input
> 
> 15:39:34
> 2019-02-26T04:39:34.825Z b57cd446-e3d7-47e9-95c7-3c2ff6bbbf16 TypeError: Cannot read property 'L' of undefined at Object.exports.fixEncryptedItemEncoding (/var/task/upgrades.js:148:24) at /var/task/upgrades.js:238:11 at nextTask (/var/task/node_modules/async/dist/async.js:5324:14) at Object.waterfall (/var/task/node_modules/async/dist/async.js:5334:5) at Object.exports.upgradeA
> 2019-02-26T04:39:34.825Z b57cd446-e3d7-47e9-95c7-3c2ff6bbbf16 TypeError: Cannot read property 'L' of undefined
> at Object.exports.fixEncryptedItemEncoding (/var/task/upgrades.js:148:24)
> at /var/task/upgrades.js:238:11
> at nextTask (/var/task/node_modules/async/dist/async.js:5324:14)
> at Object.waterfall (/var/task/node_modules/async/dist/async.js:5334:5)
> at Object.exports.upgradeAll (/var/task/upgrades.js:242:8)
> at Object.exports.upgradeConfig (/var/task/index.js:180:21)
> at Object.exports.foundConfig (/var/task/index.js:202:17)
> at /var/task/index.js:1503:37
> at /var/task/index.js:162:13
> at /var/task/node_modules/async/dist/async.js:969:16

**Comment by singhrcode** [comment]
Now i get another error

> 019-02-26T23:09:59.093Z d788204c-fbeb-4829-871e-352c792a9e6e TypeError: Cannot read property 'L' of undefined
> at exports.loadRedshiftWithManifest (/var/task/index.js:829:52)
> at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
> at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
> at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
> at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
> at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
> at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
> at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
> at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
> at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)

**Comment by singhrcode** [comment]
so many erros in files  maxRetryMS is not defined in constant.js , ProvisionedThrough attribute need to be removed from common.js , in index.js pg.connect needs to converted intool pool
