### ISSUE TITLE
ReferenceError: maxRetryMS is not defined

### ISSUE THREAD

**Issue by arvidsnet** [awslabs/aws-lambda-redshift-loader#190]
after update from version 2.6.5 to 2.6.9 I am getting occasional lambda failures with following error:
```
ReferenceError: maxRetryMS is not defined
    at Response.<anonymous> (/var/task/index.js:366:81)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
```
they do not happen very often - for last day there were 5 such errors and about 300 successful runs for the same loader config. I did not notice any pattern when it happens, also the retry is successful. Please let me know if you need any additional details.

**Comment by arvidsnet** [comment]
no error after update to 2.7.0, I suppose this is fixed with https://github.com/awslabs/aws-lambda-redshift-loader/commit/dac12be3ebc2f278584416b0f06a3a7876a2caf1
thank you, @IanMeyers
