### ISSUE TITLE
config.batchTimeoutSecs not set when using Sample script

### ISSUE THREAD

**Issue by jwswj** [awslabs/aws-lambda-redshift-loader#2]
When running the sample script:

``` bash
› ./configureSample.sh aaaa.bbbbbbbbb.us-east-1.redshift.amazonaws.com 5439 dev myusername
Password for user myusername:
create user test_lambda_load_user password 'Change-me1!';
CREATE USER
create table lambda_redshift_sample(
column_a int,
column_b int,
column_c int
);
CREATE TABLE
Enter the Region for the Redshift Load Configuration > us-east-1
Enter the S3 Bucket to use for the Sample Input > z1-trial-data
Enter the Access Key used by Redshift to get data from S3 > MYACCESSKEY
Enter the Secret Key used by Redshift to get data from S3 > MYSECRETKEY
Creating Tables in Dynamo DB if Required
Configuration for z1-trial-data/input successfully written in us-east-1

› aws s3 sync ../data s3://z1-trial-data/input
upload: ../data/sample-redshift-file-for-lambda-loader1.csv to s3://z1-trial-data/input/sample-redshift-file-for-lambda-loader1.csv
upload: ../data/sample-redshift-file-for-lambda-loader2.csv to s3://z1-trial-data/input/sample-redshift-file-for-lambda-loader2.csv
upload: ../data/sample-redshift-file-for-lambda-loader3.csv to s3://z1-trial-data/input/sample-redshift-file-for-lambda-loader3.csv
upload: ../data/sample-redshift-file-for-lambda-loader4.csv to s3://z1-trial-data/input/sample-redshift-file-for-lambda-loader4.csv
upload: ../data/sample-redshift-file-for-lambda-loader5.csv to s3://z1-trial-data/input/sample-redshift-file-for-lambda-loader5.csv
```

Gets the following processing error:

```
2015-03-07 21:00:56 UTC
2015-03-07T21:00:56.579Z    09a8edeb-c50d-11e4-bf88-3550f9dbceb4    Found Redshift Load Configuration for mybucket/input 

2015-03-07 21:00:57 UTC
2015-03-07T21:00:57.002Z    09a8edeb-c50d-11e4-bf88-3550f9dbceb4    Adding Manifest Entry for mybucket/input/sample-redshift-file-for-lambda-loader4.csv

2015-03-07 21:00:57 UTC
2015-03-07T21:00:57.742Z    09a8edeb-c50d-11e4-bf88-3550f9dbceb4    Batch Size 2 reached 

2015-03-07 21:00:57 UTC
Failure while running task: TypeError: Cannot read property 'N' of undefined
at Response.<anonymous> (/var/task/index.js:394:73)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:350:18) 
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:100:18) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10) 
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:604:14) 
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:12) 
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) 
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:22:9) 
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:606:12) 

2015-03-07 21:00:57 UTC
Process exited before completing request TypeError: Cannot read property 'N' of undefined
```

**Comment by IanMeyers** [comment]
Thanks for the fix in the sample. I've also just pushed a patch which fixes the root cause, which is a null check on config.batchTimeoutSecs
