### ISSUE TITLE
configureSample.sh fails with requests error

### ISSUE THREAD

**Issue by jstoor** [awslabs/aws-lambda-redshift-loader#29]
When running the script, we get so far and then the following error is thrown:

```
/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:34
          throw err;
                ^
TypeError: undefined is not a function
    at Response.<anonymous> (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/common.js:228:6)
    at Request.<anonymous> (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:352:18)
    at Request.callListeners (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:594:14)
    at Request.transition (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/Users/xxxxx/xxxxxx/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:596:12)
```

The following line is executed just before the error:

```
Creating Tables in Dynamo DB if Required
Configuration for dp-transform-test-01/input successfully written in us-east-1
```

Any help or advice would be appreciated.

Thank You

P.S. Thanks for the quick response to the related ticket:
https://github.com/awslabs/aws-lambda-redshift-loader/issues/28

**Comment by IanMeyers** [comment]
Right you are - this is now fixed.
