### ISSUE TITLE
Code error when loading

### ISSUE THREAD

**Issue by benburkhart1** [awslabs/aws-lambda-redshift-loader#77]
There appears to be an issue with the error handling from a PG query in the AWSLambdaRedshiftLoader-2.4.0.zip distribution.

Whenever I get an error back from Redshift, it causes a TypeError in code. Are you sure it should be relying on this detail key to exist?

2016-04-08T00:21:57.074Z e6244bb4-fd1f-11e5-abc0-91504c993fcc TypeError: Cannot call method 'find' of undefined 
at /var/task/index.js:866:23 
at Array.map (native) at null.callback (/var/task/index.js:863:27) 
at Query.handleError (/var/task/node_modules/pg/lib/query.js:106:17) 
at null.<anonymous> (/var/task/node_modules/pg/lib/client.js:171:26) 
at emit (events.js:95:17) at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:109:12) 
at Socket.emit (events.js:95:17) 
at Socket.<anonymous> (_stream_readable.js:765:14) 
at Socket.emit (events.js:92:17)

**Comment by IanMeyers** [comment]
Ugh - right you are - sorry about that. Fixed in an in-place update of 2.4.0.

**Comment by benburkhart1** [comment]
Left a comment on your commit, still think this would have issues, getting prepped to do another test, but err.detail is undefined, and I'm not sure where you'd expect that to be defined at (looking at the code in the callstack it's not obvious to me)

**Comment by IanMeyers** [comment]
The 'detail' element is provided by the pgError, and should be there - do let me know if you see differently.

**Comment by benburkhart1** [comment]
Ok I am no longer able to reproduce this issue. Thank you so much.
